# Generated by Django 6.0.6 on 2026-10-01 11:46

from django.db import migrations, models


HOME_IMAGE_URLS = {
    'Walnut Brownie': 'https://images.unsplash.com/photo-1599785209707-a456fc1337bb?auto=format&fit=crop&w=500&q=80',
    'Chocolate Mousse Cake': 'https://images.unsplash.com/photo-1486427944299-d1955d23e34d?auto=format&fit=crop&w=500&q=80',
    'Brownie Bowls': 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=500&q=80',
    'Veg Classic Pizza': 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=500&q=80',
}


def seed_home_images(apps, schema_editor):
    Item = apps.get_model('app', 'Item')
    for name, image_url in HOME_IMAGE_URLS.items():
        Item.objects.filter(name=name, category='home').update(image_url=image_url)


def clear_home_images(apps, schema_editor):
    Item = apps.get_model('app', 'Item')
    Item.objects.filter(category='home', name__in=HOME_IMAGE_URLS).update(image_url='')


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.RunPython(seed_home_images, clear_home_images),
    ]
