# Generated by Django 6.0.6 on 2026-10-01 12:55

from django.db import migrations, models


SEEDED_HOME_IMAGES = {
    'Walnut Brownie': 'https://images.unsplash.com/photo-1599785209707-a456fc1337bb?auto=format&fit=crop&w=500&q=80',
    'Chocolate Mousse Cake': 'https://images.unsplash.com/photo-1486427944299-d1955d23e34d?auto=format&fit=crop&w=500&q=80',
    'Brownie Bowls': 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=500&q=80',
    'Veg Classic Pizza': 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=500&q=80',
}


def clear_seeded_home_images(apps, schema_editor):
    Item = apps.get_model('app', 'Item')
    for name, image_url in SEEDED_HOME_IMAGES.items():
        Item.objects.filter(name=name, category='home', image_url=image_url).update(image_url='')


def restore_seeded_home_images(apps, schema_editor):
    Item = apps.get_model('app', 'Item')
    for name, image_url in SEEDED_HOME_IMAGES.items():
        Item.objects.filter(name=name, category='home', image_url='').update(image_url=image_url)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_item_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(clear_seeded_home_images, restore_seeded_home_images),
    ]
