# Generated by Django 6.0.6 on 2026-10-01 13:07

from django.db import migrations, models


MENU_GROUPS = {
    'brownie-menu': ['Fudgy Brownie', 'Cakey Brownie', 'Chewy Brownie', 'Walnut Brownie'],
    'cupcake-menu': ['Chocolate Cupcakes', 'Vanilla Cupcake', 'Strawberry Cupcakes', 'Customize Cupcakes'],
    'pizza-menu': ['Veg Classic Pizza', 'Corn Cheese Pizza', 'Chicken Pizza', 'Onion Pizza'],
}


def group_existing_products(apps, schema_editor):
    Item = apps.get_model('app', 'Item')
    for menu_group, names in MENU_GROUPS.items():
        Item.objects.filter(category='freshly-baked', name__in=names).update(menu_group=menu_group)


def clear_product_groups(apps, schema_editor):
    Item = apps.get_model('app', 'Item')
    Item.objects.filter(category='freshly-baked', menu_group__in=MENU_GROUPS).update(menu_group='')


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='menu_group',
            field=models.CharField(blank=True, choices=[('brownie-menu', "Brownie's"), ('cupcake-menu', "Cupcake's"), ('pizza-menu', "Pizza's"), ('other-menu', 'Other')], default='', max_length=20),
        ),
        migrations.RunPython(group_existing_products, clear_product_groups),
    ]
